version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - VITE_AWS_S3_URL=http://minio:9000
      - VITE_AWS_S3_BASKET=mysigmail
      - VITE_AWS_S3_ID=minioadmin
      - VITE_AWS_S3_KEY=minioadmin
      - VITE_AWS_S3_REGION=us-east-1

  # minio:
  #   image: minio/minio
  #   ports:
  #     - '9000:9000'
  #     - '9001:9001'
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   volumes:
  #     - minio-data:/data
  #   command: server /data --console-address :9001

volumes:
  minio-data:
